Don't look for `get_config()` if the object is not instantiated
Some libraries put `type`s in their config, so `get_config` cannot be called: https://github.com/tensorflow/models/blob/325e10e2602e23c8a2d33a611c6b3286372b0b1a/official/nlp/modeling/layers/transformer.py#L385

```
config = instance.get_config()
TypeError: MultiHeadAttention.get_config() missing 1 required positional argument: 'self'
```
PiperOrigin-RevId: 580905909